# Generated by Django 2.2.3 on 2019-08-12 10:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='short_links', to=settings.AUTH_USER_MODEL),
        ),
    ]
