# Generated by Django 2.2.3 on 2019-08-12 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shortlink_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='shortlinks', to=settings.AUTH_USER_MODEL),
        ),
    ]
