# Generated by Django 2.2.3 on 2019-08-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190812_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='redirect_count',
            field=models.IntegerField(default=0),
        ),
    ]
